#!/bin/bash
ssh_setup() {
  local t=$1
      case $t in
          gen)
             local comment=${2:-}
              mkdir -p "$HOME/.ssh"
              chmod 700 ~/.ssh 
              ssh-keygen -t ed25519 -C "$comment" -f "$HOME/.ssh/id_ed25519_$comment" -N ""
              echo "Public key for $comment saved to $HOME/.ssh/id_ed25519_$comment.pub"
              cat "$HOME/.ssh/id_ed25519_$comment.pub"
               ;;
          add)
              local key=${2:-}
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh 
              echo "$key" >> ~/.ssh/authorized_keys
              chmod 600 ~/.ssh/authorized_keys &&
              echo "DONE ADDING PUBKEY"
              ;;
          *)
              echo "unknown agrument" && return 1
              ;;
      esac      
  }




create_file(){

    if [[ ! -f "$HOME/.ssh/authorized_keys" ]]; then
         mkdir -p "$(dirname "$HOME/.ssh/authorized_keys")" &&
         touch "$HOME/.ssh/authorized_keys" &&
         echo "Created $HOME/.ssh/authorized_keys"
    fi

    if grep -q "OPPO" $HOME/.local/bin/env 2>/dev/null; then
        echo "JOE_ENV already configured in $SHELL_RC"
    else
        cat > "$HOME/.local/bin/env" << "EOF"
# SSH Mesh — Fresh 2026-08-19
# 4-node mesh via Tailscale IPs (100.x.x.x)
# Regenerated by Alpha — all keypairs fresh, all authorized_keys trust wsl/mumu/window/termux

# ───────────────────────────────────────────────────────┐
#                    JOE’S ENVIRONMENT                    │
#    (Tailscale 100.x.x.x nodes — private mesh only)     │
# ───────────────────────────────────────────────────────┘

# → Add these two lines to ~/.bashrc (after NVM, before other exports)
# export JOE_ENV=oppo
# export MY_DEVICE=${OPPO:-$JOE_ENV}

# ───────────────────────────────────────────────────────┐
#                       OPPO (WSL/ubuntu)                  │
# ───────────────────────────────────────────────────────┘

export JOE_ENV=oppo
export MY_DEVICE=oppo

# paths
export PATH="$HOME/.local/lib/openclaw/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# alias sets
alias cls="clear"
alias h='cd $HOME'
alias cls='printf "\033[2J\033[H"'
alias dir='ls -hF'
alias ll='ls -laF'
alias ll='ls -laF'
alias ls="eza --icons"
alias ll="eza --icons -la"
alias c='curl -sL'
alias j='jps'
alias nv='nvm use default'
alias nv= "echo '$HOME/.nvm'"
alias j= "echo '$HOME/.local/bin/joe.sh'"
alias py='python3'
alias npm= "echo '$HOME/.nvm/versions/node/v*/bin/npm'"


# ⭐ USER HOMEFOLDERS — set after cloning
export UHOME="$HOME/ssot/profiles/$MY_DEVICE"
if [ ! -d "$UHOME" ]; then mkdir -p "$UHOME"; fi

# ⭐ NODE/PNPM VERSIONS — set after running nvm
export NVM_NODE_PATH="$HOME/.local/share/pnpm"
if [ ! -d "$NVM_NODE_PATH" ]; then mkdir -p "$NVM_NODE_PATH"; fi
alias nv_npm="$NVM_NODE_PATH/npm"

# ⭐ PROGRAM PATHS — must exist after first `setup.sh`
export SSOT="$HOME/ssot"
export JOES="$HOME/ssot/joe.sh"
export SSOTB="$HOME/ssot/.bash_helper"
if [ ! -f "$JOES" ]; then cp -n "$SSOT/joe.sh" "$JOES"; fi
if [ ! -f "$SSOTB" ]; then cp -n "$SSOT/bash_helper" "$SSOTB"; fi

# ⭐ DEVICE OVERRIDES

# ⭐ REMOTE MACHINE HOSTNAMES (Tailscale IPs) – never public IPs
export OPPOTL="oppo.ts.local"

# ⭐ KEY PATHS
export SSH_DIR="$HOME/.ssh"
if [ ! -d "$SSH_DIR" ]; then mkdir -p "$SSH_DIR"; fi

export ID_ED25519_OPPO="$SSH_DIR/id_ed25519_$MY_DEVICE"

export OPPOTL_PUB_KEY=$(cat "$ID_ED25519_OPPO.pub" 2>/dev/null)
if [ ! -f "$ID_ED25519_OPPO" ]; then
    echo "⚡ No SSH key for $MY_DEVICE found → generating…"
    ssh-keygen -t ed25519 -C "$MY_DEVICE" -f "$ID_ED25519_OPPO" -N ""
    echo "Public key for $MY_DEVICE saved to $ID_ED25519_OPPO.pub"
    echo "Public key for $MY_DEVICE copied to clipboard"
fi

# Add ALL SSH keys from .ssh/* to ssh-agent

if [[ -n "$SSH_AUTH_SOCK" ]]; then
    ssh-add "$ID_ED25519_OPPO" 2>/dev/null || true
fi

# ⭐ REMOTE ENV FILES (optional)
export REMOTE_ENV_BASE="$HOME/.remote_env"
if [ -d "$REMOTE_ENV_BASE" ]; then
    export OPPOTL_ENV="$REMOTE_ENV_BASE/oppo.env"
    [ -f "$OPPOTL_ENV" ] && . "$OPPOTL_ENV"
fi

# ⭐ SSH CONFIG MERGE (critical for meshnetworking)
# If you don’t want to append to existing config, comment out the source below

if [ ! -f "$SSH_DIR/config" ]; then
    touch "$SSH_DIR/config"
    chmod 600 "$SSH_DIR/config"
fi

if grep -q "OPPOTL" "$SSH_DIR/config" 2>/dev/null; then
    echo "SSH config already contains entries for OPPOTL – skipping merge"
else
    cat > "$SSH_DIR/config_entry_oppotl" << "EOF"
# ─────────────── OPPOTL (WSL/ubuntu) ───────────────
Host oppo.ts.local
    HostName oppo.ts.local
    User usercivenz
    IdentityFile $HOME/.ssh/id_ed25519_oppo
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    UserKnownHostsFile $HOME/.ssh/known_hosts
    ForwardAgent yes
    # Optional: tailscale ssh tunnel (uncomment if using)
    # ProxyCommand tailscale ssh --tunnel=oppo.ts.local -- ssh -W %h:%p
EOF
    echo "Added OPPOTL SSH config entry"
fi

# ─────────────── REMOTE TOOLS ───────────────
# (Optional tools to run on the remote machine)

# ─────────────── AUTOSTART COMMANDS ───────────────
# Commands to run after login on this device (oppo)
# Example: `if [[ "$MY_DEVICE" == "oppo" ]]; then tmux attach-session -t dev || tmux new-session -s dev; fi`

EOF
}